### ISSUE TITLE
Gmap API

### ISSUE THREAD

**Issue by 2braincells2go** [libeo-vtt/jquery-custom-map#2]
Very nice script!

Is it safe to use without API key? Like to use but worried it be disabled later.

Also, is there way to disable one of the makers? I try:

`htmlMarkers: false,
hideHtmlMarkers: true,`

But no change.

Many thanks in advance,

Woody

**Comment by mykthex** [comment]
You should definitly get a free API key. Google does not allow using Maps without an api key anymore. 

What do you mean disable one of the markers? You can simply ignore the js markers (empty array) and/or put no html markers.

**Comment by 2braincells2go** [comment]
Thanks for reply.

I did not see any area for API key so was wondering if only displaying map would be safe.

I was getting two markers. One from Gmaps and the custom one. Think I figured that out.

Thanks again.
